# Site settings
title: 暂存灵魂
email: ismyway7@sina.com
url: https://hgmyway.github.io
description: "任是无情也动人"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: hgmyway.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #  - title: 微微
   # url: http://weiwei2013.github.io/page2/
 # - title: twitter
  #  url: https://twitter.com/SBootstrap
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
   # url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
